#!/bin/sh
if ! command -v openssl >/dev/null 2>&1 ; then
  echo "Error: Could not find openssl in \$PATH: $PATH"
  exit 1
fi

if test -f spiderFeet.key; then
  echo "Error: spiderFeet.key already exists"
  exit 1
fi

if test -f spiderFeet.crt; then
  echo "Error: spiderFeet.crt already exists"
  exit 1
fi

openssl req -new -newkey rsa:4096 -sha256 -x509 -days 365 -nodes -out spiderFeet.crt -keyout spiderFeet.key -subj "/CN=localhost"

chmod 600 spiderFeet.crt
chmod 600 spiderFeet.key
