#!/usr/bin/env bash
# Install the six quarantine CLI tools on WSL Ubuntu (Stage 5 — #806 / #807).
# No sudo required — builds user-local under ~/.local/spiderfeet-cli
# Usage: bash .seed/scripts/install_wsl_cli_tools.sh
set -euo pipefail

CLI_ROOT="${SPIDERFEET_CLI_ROOT:-$HOME/.local/spiderfeet-cli}"
BIN_DIR="$CLI_ROOT/bin"
MANIFEST="$CLI_ROOT/manifest.env"

echo "==> SpiderFeet WSL CLI install (root: $CLI_ROOT)"
mkdir -p "$CLI_ROOT" "$BIN_DIR"
cd "$CLI_ROOT"

ensure_apt_deps() {
  local missing=()
  for pkg in make gcc ruby ruby-dev nodejs npm nbtscan onesixtyone; do
    case "$pkg" in
      make) command -v make >/dev/null || missing+=("$pkg") ;;
      gcc) command -v gcc >/dev/null || missing+=("build-essential") ;;
      ruby) command -v ruby >/dev/null || missing+=("ruby" "ruby-dev") ;;
      ruby-dev) ;;
      nodejs) command -v node >/dev/null || missing+=("nodejs") ;;
      npm) command -v npm >/dev/null || missing+=("npm") ;;
      nbtscan) command -v nbtscan >/dev/null || missing+=("nbtscan") ;;
      onesixtyone) command -v onesixtyone >/dev/null || missing+=("onesixtyone") ;;
    esac
  done
  if ((${#missing[@]})); then
    echo "==> Installing apt packages: ${missing[*]}"
    if command -v sudo >/dev/null && sudo -n true 2>/dev/null; then
      sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
      sudo DEBIAN_FRONTEND=noninteractive apt-get install -y "${missing[@]}"
    else
      echo "Run as WSL root: apt-get install -y ${missing[*]}" >&2
      exit 1
    fi
  fi
}

for cmd in git python3; do
  command -v "$cmd" >/dev/null || {
    echo "ERROR: missing $cmd" >&2
    exit 1
  }
done

python3 -m pip --version >/dev/null 2>&1 || python3 -m pip install --user pip
export PATH="$HOME/.local/bin:$PATH"
ensure_apt_deps

echo "==> CMSeeK"
if [[ ! -f "$CLI_ROOT/CMSeeK/cmseek.py" ]]; then
  git clone --depth 1 https://github.com/Tuhinshubhra/CMSeeK
fi
python3 -m pip install --user -r "$CLI_ROOT/CMSeeK/requirements.txt" 2>/dev/null \
  || python3 -m pip install --user -r "$CLI_ROOT/CMSeeK/requirements.txt" --break-system-packages
chmod +x "$CLI_ROOT/CMSeeK/cmseek.py"

echo "==> testssl.sh"
if [[ ! -f "$CLI_ROOT/testssl.sh/testssl.sh" ]]; then
  git clone --depth 1 https://github.com/drwetter/testssl.sh.git
fi
chmod +x "$CLI_ROOT/testssl.sh/testssl.sh"

echo "==> WhatWeb"
if [[ ! -f "$CLI_ROOT/WhatWeb/whatweb" ]]; then
  git clone --depth 1 https://github.com/urbanadventurer/WhatWeb
fi
chmod +x "$CLI_ROOT/WhatWeb/whatweb"
gem install addressable --user-install 2>/dev/null || true

echo "==> nbtscan (source build)"
if [[ ! -x "$BIN_DIR/nbtscan" ]]; then
  if command -v nbtscan >/dev/null 2>&1; then
    ln -sf "$(command -v nbtscan)" "$BIN_DIR/nbtscan"
  else
    rm -rf "$CLI_ROOT/nbtscan-src"
    git clone --depth 1 https://github.com/lkarsten/nbtdump.git "$CLI_ROOT/nbtscan-src" 2>/dev/null \
      || git clone --depth 1 https://github.com/charleswiltgen/nbtscan.git "$CLI_ROOT/nbtscan-src"
    make -C "$CLI_ROOT/nbtscan-src" 2>/dev/null || make -C "$CLI_ROOT/nbtscan-src" nbtscan
    install -m 0755 "$CLI_ROOT/nbtscan-src/nbtscan" "$BIN_DIR/nbtscan" 2>/dev/null \
      || cp "$CLI_ROOT/nbtscan-src/nbtscan" "$BIN_DIR/nbtscan"
  fi
fi

echo "==> onesixtyone (source build)"
if [[ ! -x "$BIN_DIR/onesixtyone" ]]; then
  if command -v onesixtyone >/dev/null 2>&1; then
    ln -sf "$(command -v onesixtyone)" "$BIN_DIR/onesixtyone"
  else
    rm -rf "$CLI_ROOT/onesixtyone-src"
    git clone --depth 1 https://github.com/trailofbits/onesixtyone.git "$CLI_ROOT/onesixtyone-src"
    make -C "$CLI_ROOT/onesixtyone-src"
    install -m 0755 "$CLI_ROOT/onesixtyone-src/onesixtyone" "$BIN_DIR/onesixtyone"
  fi
fi

echo "==> Wappalyzer (legacy AliasIO CLI — optional, often blocked)"
WAPP_CLI=""
if [[ ! -d "$CLI_ROOT/wappalyzer/.git" ]]; then
  rm -rf "$CLI_ROOT/wappalyzer"
  if timeout 120 git clone --depth 1 https://github.com/AliasIO/wappalyzer.git "$CLI_ROOT/wappalyzer"; then
    if [[ -f "$CLI_ROOT/wappalyzer/package.json" ]]; then
      (cd "$CLI_ROOT/wappalyzer" && timeout 300 npm install --legacy-peer-deps) || true
    fi
  else
    echo "WARN: wappalyzer clone skipped (network/timeout); module may stay tool_missing"
  fi
fi
cd "$CLI_ROOT"

WAPP_CLI=""
for candidate in \
  "$CLI_ROOT/wappalyzer/src/drivers/npm/cli.js" \
  "$CLI_ROOT/wappalyzer/src/drivers/webextension/cli.js"; do
  if [[ -f "$candidate" ]]; then
    WAPP_CLI="$candidate"
    break
  fi
done

NODE_BIN="$(command -v node)"
NBT_PATH="$BIN_DIR/nbtscan"
[[ -x "$NBT_PATH" ]] || NBT_PATH="$(command -v nbtscan || true)"
O161_PATH="$BIN_DIR/onesixtyone"
[[ -x "$O161_PATH" ]] || O161_PATH="$(command -v onesixtyone || true)"

cat >"$MANIFEST" <<EOF
# Generated by install_wsl_cli_tools.sh
export SPIDERFEET_CLI_ROOT="$CLI_ROOT"
export SPIDERFEET_CMSEEK_PATH="$CLI_ROOT/CMSeeK/cmseek.py"
export SPIDERFEET_TESTSSL_PATH="$CLI_ROOT/testssl.sh/testssl.sh"
export SPIDERFEET_WHATWEB_PATH="$CLI_ROOT/WhatWeb/whatweb"
export SPIDERFEET_NBTSCAN_PATH="$NBT_PATH"
export SPIDERFEET_ONESIXTYONE_PATH="$O161_PATH"
export SPIDERFEET_NODE_PATH="$NODE_BIN"
export SPIDERFEET_WAPPALYZER_PATH="${WAPP_CLI:-}"
export PATH="$BIN_DIR:\$PATH"
EOF

echo "==> Manifest: $MANIFEST"
cat "$MANIFEST"
echo "==> Probe"
source "$MANIFEST"
for label path in \
  cmseek "$SPIDERFEET_CMSEEK_PATH" \
  testssl "$SPIDERFEET_TESTSSL_PATH" \
  whatweb "$SPIDERFEET_WHATWEB_PATH" \
  nbtscan "$SPIDERFEET_NBTSCAN_PATH" \
  onesixtyone "$SPIDERFEET_ONESIXTYONE_PATH" \
  wappalyzer "$SPIDERFEET_WAPPALYZER_PATH"; do
  if [[ -n "$path" && ( -f "$path" || -x "$path" ) ]]; then
    echo "  OK $label"
  else
    echo "  MISSING $label"
  fi
done
echo "==> Done"
