#!/usr/bin/env python3
"""Generate SPEC-018 A1 GSE fixture proof matrix (corpus graphs only)."""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Mapping, Tuple

import yaml

from spiderfeet_v2.workflow.gse_eval import evaluate_output_vars

ROOT = Path(__file__).resolve().parents[2]
EXAMPLE = ROOT / ".seed/12A_Workflow_YAML_Example.yaml"
NS = ROOT / ".docs/docs-for-cli-tools/nugget_structure"
OUT = ROOT / ".docs/docs-for-cli-tools/SPEC018_A1_GSE_PROOF.md"

# Seed targets used when re-evaluating subfinder (A2 union with workflow inputs)
FIXTURE_INPUTS: Dict[str, List[str]] = {
    "sfp_cli_subfinder": ["theupside.com.au"],
}

# Canonical corpus fixtures per structure docs / 12A chain targets
FIXTURES: Dict[str, Path] = {
    "sfp_cli_subfinder": NS / "subfinder_corporate_upside_au_passive_cs_proposed_nuggets_edges.json",
    "sfp_cli_nmap": NS / "nmap_tcp_top_ports_permissive_proposed_nuggets_edges.json",
    "sfp_cli_httpx": NS / "httpx_from_subfinder_upside_au_proposed_nuggets_edges.json",
    "sfp_cli_katana": NS / "katana_from_httpx_upside_com_proposed_nuggets_edges.json",
}


def _load_graph(path: Path) -> Mapping[str, Any]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    return {"nodes": raw.get("nodes", []), "edges": raw.get("edges", [])}


def _nugget_counts(graph: Mapping[str, Any]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for node in graph.get("nodes", []):
        nid = node.get("nugget_id", "?")
        counts[nid] = counts.get(nid, 0) + 1
    return dict(sorted(counts.items()))


def _evaluate_step(
    step: Mapping[str, Any],
    fixture: Path,
    *,
    step_id: str,
) -> Tuple[Dict[str, List[str]], Dict[str, int]]:
    graph = _load_graph(fixture)
    workflow_inputs = {"targets": FIXTURE_INPUTS.get(step_id, [])}
    vars_out = evaluate_output_vars(
        step,
        graph,
        workflow_inputs=workflow_inputs if workflow_inputs["targets"] else None,
    )
    return vars_out, _nugget_counts(graph)


def _md_table(rows: List[List[str]]) -> str:
    if not rows:
        return ""
    header = rows[0]
    lines = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join("---" for _ in header) + " |",
    ]
    for row in rows[1:]:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def main() -> int:
    doc = yaml.safe_load(EXAMPLE.read_text(encoding="utf-8"))
    steps_by_id = {s["id"]: s for s in doc["steps"]}

    sections: List[str] = [
        "# SPEC-018 A1 — GSE fixture proof matrix",
        "",
        "Generated by `.seed/scripts/spec018_gse_proof.py` against corpus graphs only.",
        f"Workflow: `{EXAMPLE.relative_to(ROOT).as_posix()}`",
        "",
        "## Summary table",
        "",
    ]

    EXPECTED: Dict[str, str] = {
        "apex_domains": "Non-empty apex DOMAIN_NAME nodes (no outbound `had` → DOMAIN_NAME_PARENT)",
        "subdomains": "Child DOMAIN_NAME nodes with outbound `had` → DOMAIN_NAME_PARENT",
        "all_domains": "Union of apex + subdomains + normalized workflow targets (distinct)",
        "ip_port_list": "Non-empty `host:port` from HOST×IP×PORT contains walk",
        "live_hosts": "Non-empty DOMAIN_NAME list from httpx scan graph",
        "crawl_urls": "Non-empty URL/domain list from katana scan graph",
    }

    summary_rows: List[List[str]] = [
        ["Step", "Output var", "Fixture", "Count", "Empty?", "Expected", "Sample (≤3)"],
    ]

    for step_id, fixture in FIXTURES.items():
        step = steps_by_id[step_id]
        vars_out, nugget_counts = _evaluate_step(step, fixture, step_id=step_id)
        sections.append(f"## {step_id}")
        sections.append("")
        sections.append(f"Fixture: `{fixture.relative_to(ROOT).as_posix()}`")
        sections.append("")
        sections.append("**Nugget counts in fixture:**")
        sections.append("")
        for nid, cnt in nugget_counts.items():
            sections.append(f"- `{nid}`: {cnt}")
        sections.append("")

        for var_name, values in vars_out.items():
            empty = "yes" if len(values) == 0 else "no"
            sample = ", ".join(repr(v) for v in values[:3]) or "—"
            summary_rows.append(
                [
                    step_id,
                    var_name,
                    fixture.name,
                    str(len(values)),
                    empty,
                    EXPECTED.get(var_name, "—"),
                    sample,
                ]
            )
            sections.append(f"### `{var_name}`")
            sections.append("")
            sections.append(f"- **Count:** {len(values)}")
            sections.append(f"- **Empty:** {empty}")
            if values:
                sections.append(f"- **Sample:** {', '.join(repr(v) for v in values[:5])}")
            sections.append("")

    sections.insert(6, _md_table(summary_rows))
    sections.append("")

    # Nerva / Nuclei hypotheses (12A has no output.vars — document chain inputs)
    sections.extend(
        [
            "## Nerva / Nuclei hypotheses (A2 scope)",
            "",
            "12A has **no** `output.vars` on `sfp_cli_nerva` or `sfp_cli_nuclei`. Failures are upstream chain / input binding issues.",
            "",
            "### Nerva (`sfp_cli_nerva`)",
            "",
            "- **Input:** `$steps.sfp_cli_nmap.vars.ip_port_list`",
            "- **12A GSE:** HOST `--contains-->` IPV4_ADDRESS + PORT → `host:port` strings",
            "- **Corpus nmap graph** (`nmap_tcp_top_ports_permissive`) uses `PORT` nugget_id (not `TCP_PORT_OPEN`) under HOST via `contains` — matches evaluator test graph in `test_dsl.py`.",
            "- **A1 result:** corpus nmap fixture yields **4** `ip_port_list` values — GSE binding is sound on canonical graph.",
            "- **Hypothesis:** if live Nerva gets empty input, check (1) live nmap graph topology differs from corpus, (2) adapter emits TCP_PORT_OPEN instead of PORT, (3) missing HOST `contains` edges — not Nerva adapter in isolation.",
            "",
            "### Subfinder apex gap (A2)",
            "",
            "- **A1 result:** `apex_domains` **empty** while `subdomains` = 27 = all DOMAIN_NAME nodes on upside_au fixture.",
            "- **Hypothesis:** subfinder graph attaches DOMAIN_NAME_PARENT via `had` on every domain (including registrable apex), so `not related had DOMAIN_NAME_PARENT` matches nothing. Fix in A2 (GSE or adapter edge direction).",
            "",
            "### Nuclei (`sfp_cli_nuclei`)",
            "",
            "- **Input:** `$steps.sfp_cli_katana.vars.crawl_urls`",
            "- **Katana proof above:** `crawl_urls` count on `katana_from_httpx_upside_com` fixture — if zero, Nuclei skips (`empty: skip_step`).",
            "- **Hypothesis:** Nuclei timeout is argv/timeout (900s) not GSE; empty skip is katana GSE or upstream httpx `live_hosts`.",
            "",
        ]
    )

    OUT.write_text("\n".join(sections) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")
    for row in summary_rows[1:]:
        print("\t".join(row).encode("ascii", errors="replace").decode("ascii"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
