#!/usr/bin/env python3
"""Sync SpiderFeet Subscriptions module keys into gitignored .tools/pius.env for harvest."""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
PIUS_ENV = REPO_ROOT / ".tools" / "pius.env"
PIUS_ENV_EXAMPLE = REPO_ROOT / ".tools" / "pius.env.example"

# SpiderFeet module_id -> PIUS environment variable(s)
MODULE_TO_PIUS_ENV = {
    "sfp_shodan": ["SHODAN_API_KEY"],
    "sfp_securitytrails": ["SECURITYTRAILS_API_KEY"],
    "sfp_censys": ["CENSYS_API_TOKEN", "CENSYS_ORG_ID"],
    "sfp_builtwith": ["BUILTWITH_API_KEY"],
    "sfp_whoxy": ["WHOXY_API_KEY"],
    "sfp_binaryedge": ["BINARYEDGE_API_KEY"],
    "sfp_github": ["GITHUB_TOKEN"],
}


def main() -> int:
    sys.path.insert(0, str(REPO_ROOT))
    from spiderfeet.api.bootstrap import get_runtime

    runtime = get_runtime()
    modules = runtime.config.get("__modules__") or {}
    lines = [
        "# Auto-generated by sync_pius_env.py — do not commit (.tools/ is gitignored)",
        "# Populate missing keys via widget Subscriptions tab, then re-run this script.",
        "",
    ]
    for module_id, env_names in MODULE_TO_PIUS_ENV.items():
        mod = modules.get(module_id) or {}
        opts = mod.get("opts") or {}
        api_key = str(opts.get("api_key") or "").strip()
        org_id = str(opts.get("org_id") or opts.get("api_uid") or "").strip()
        for env_name in env_names:
            if env_name == "CENSYS_ORG_ID":
                value = org_id
            elif env_name == "GITHUB_TOKEN":
                value = api_key or str(opts.get("token") or "").strip()
            else:
                value = api_key
            if value:
                lines.append(f'{env_name}="{value}"')
            else:
                lines.append(f"# {env_name}=  # configure via Subscriptions → {module_id}")

    PIUS_ENV.parent.mkdir(parents=True, exist_ok=True)
    PIUS_ENV.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {PIUS_ENV.relative_to(REPO_ROOT)} ({sum(1 for l in lines if '=' in l and not l.strip().startswith('#'))} keys set)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
