"""Push credential values into registered CLI application env files."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Set

REPO_ROOT = Path(__file__).resolve().parents[2]
from spiderfeet.credentials.registry import cli_app_defaults, list_providers, provider_by_id
from spiderfeet.credentials.store import resolve_env_value
from spiderfeet.settings.cli_apps import get_cli_app_registry, resolve_env_file_path

_ENV_VAR_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
_ALLOWED_ENV_FILES = {
    ".tools/pius.env",
    ".tools/pius.env.example",
}


def _validate_env_var(name: str) -> None:
    if not _ENV_VAR_RE.match(name):
        raise ValueError(f"Invalid env var name: {name}")


def _validate_env_file(path: Path) -> None:
    try:
        rel = path.resolve().relative_to(REPO_ROOT.resolve())
    except ValueError as exc:
        raise ValueError(f"Env file must be under repo root: {path}") from exc
    rel_posix = rel.as_posix()
    if rel_posix not in _ALLOWED_ENV_FILES and not rel_posix.startswith(".tools/"):
        raise ValueError(f"Env file path not allowlisted: {rel_posix}")


def build_env_lines_for_app(cli_app_id: str, runtime_config: Dict[str, Any]) -> List[str]:
    registry = get_cli_app_registry(runtime_config)
    app_row = registry.get(cli_app_id) or cli_app_defaults().get(cli_app_id)
    if not app_row or not app_row.get("enabled", True):
        return []

    lines = [
        f"# Auto-generated by SpiderFeet credential sync — do not commit",
        f"# CLI app: {cli_app_id}",
        "",
    ]
    seen_vars: Set[str] = set()

    for provider in list_providers():
        if cli_app_id not in (provider.get("cli_apps") or []):
            continue
        for mapping in provider.get("env_mappings") or []:
            if mapping.get("cli_app") != cli_app_id:
                continue
            env_var = str(mapping.get("env_var") or "")
            from_opt = str(mapping.get("from_opt") or "api_key")
            _validate_env_var(env_var)
            if env_var in seen_vars:
                continue
            seen_vars.add(env_var)
            value = resolve_env_value(provider, from_opt, runtime_config)
            if value:
                escaped = value.replace("\\", "\\\\").replace('"', '\\"')
                lines.append(f'{env_var}="{escaped}"')
            else:
                lines.append(f"# {env_var}=  # configure via Subscriptions")
    return lines


def sync_cli_app(cli_app_id: str, runtime_config: Dict[str, Any]) -> Optional[Path]:
    registry = get_cli_app_registry(runtime_config)
    app_row = registry.get(cli_app_id) or cli_app_defaults().get(cli_app_id)
    if not app_row:
        return None
    env_file = resolve_env_file_path(app_row)
    if not env_file:
        return None
    _validate_env_file(env_file)
    lines = build_env_lines_for_app(cli_app_id, runtime_config)
    env_file.parent.mkdir(parents=True, exist_ok=True)
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return env_file


def sync_cli_apps_for_provider(provider_id: str, runtime_config: Dict[str, Any]) -> List[str]:
    provider = provider_by_id(provider_id)
    if not provider:
        return []
    synced: List[str] = []
    for app_id in provider.get("cli_apps") or []:
        path = sync_cli_app(str(app_id), runtime_config)
        if path:
            synced.append(str(path.relative_to(REPO_ROOT)))
    return synced


def sync_all_registered_cli_apps(runtime_config: Dict[str, Any]) -> Dict[str, str]:
    results: Dict[str, str] = {}
    registry = get_cli_app_registry(runtime_config)
    for app_id, row in registry.items():
        if not row.get("enabled", True):
            continue
        if not row.get("env_file") and not cli_app_defaults().get(app_id, {}).get("default_env_file"):
            continue
        path = sync_cli_app(app_id, runtime_config)
        if path:
            results[app_id] = str(path)
    return results
